// <auto-generated />
namespace TestProject2.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creat_StudentEntiy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creat_StudentEntiy));
        
        string IMigrationMetadata.Id
        {
            get { return "201812091619576_Creat_StudentEntiy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
